[package]
name = "dbsdk-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
cargo_toml = "0.11.6"
fs_extra = "1.2.0"